name: "✨ Feature Request"
description: "Suggest a new feature or enhancement"
title: "FEAT:"
labels: [Feature, Enhancement]
body:
  - type: checkboxes
    attributes:
      label: "Is there an existing feature request for this?"
      description: "Please search to see if a similar feature request already exists."
      options:
        - label: "I have searched the existing feature requests"
          required: true
  - type: textarea
    attributes:
      label: "Describe the feature"
      description: "A detailed description of the feature or enhancement you are suggesting."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional context"
      description: "Any other context or screenshots about the feature request."
  - type: checkboxes 
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true 
        - label: "I have read the project's contributing guidelines."
          required: true
        - label: "I want to work on this feature"
